### PR TITLE
fix: fil numbers conversion for logs, allocation request transaction

### PR DESCRIPTION
**Pull request by bahadylbekov**
This PR includes fixes for SDK after an integration testing

### CODE REVIEW

**Comment by kmadorin** [comment]
Old param in allocation get-allocation command. Should be -m, not -o
 
 collectif-go-sdk git:(integration-fixes) ✗ ./collectif-go-sdk allocation get-allocation

Error: required flag(s) "minerAddr" not set
Usage:
  collective-go-sdk allocation get-allocation [flags]

Flags:
  -h, --help               help for get-allocation
  -o, --minerAddr string   Miner actor address (either ID address or actor address)

**Comment by kmadorin** [comment]
It will be better to add FIL in the end, so units will be clear to SPs
Available collateral:  3396.400000000000000000
Locked collateral:  3.600000000000000000

**Comment by bahadylbekov** [comment]
> Old param in allocation get-allocation command. Should be -m, not -o
> 
> collectif-go-sdk git:(integration-fixes) ✗ ./collectif-go-sdk allocation get-allocation
> 
> Error: required flag(s) "minerAddr" not set Usage: collective-go-sdk allocation get-allocation [flags]
> 
> Flags: -h, --help help for get-allocation -o, --minerAddr string Miner actor address (either ID address or actor address)

Changed the flag to -m

**Comment by bahadylbekov** [comment]
> It will be better to add FIL in the end, so units will be clear to SPs
> Available collateral: 3396.400000000000000000
> Locked collateral: 3.600000000000000000

Added FIL at the end of each comment

**Pull request merged**
